services:
  frontend:
    container_name: frontend-container-poc-remix
    build:
      context: ./frontend/
      target: dev
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"