services:
  db:
    build:
      context: .
      dockerfile: ./dockerfiles/db.Dockerfile
    container_name: nextjs-go-postgres-db-instance
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - trigger
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  api:
    build:
      context: .
      dockerfile: ./dockerfiles/api.Dockerfile
    container_name: nextjs-go-postgres-api-instance
    ports:
      - "8000:8000"
    networks:
      - trigger
    depends_on:
      - db

  web:
    container_name: nextjs-go-postgres-web-instance
    build:
      context: .
      target: dev
      dockerfile: ./dockerfiles/web.Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    networks:
      - trigger
    depends_on:
      - api

volumes:
  postgres-data:
    driver: local

networks:
  trigger:
    driver: bridge
