services:
  db:
    image: postgres:15
    container_name: db-instance
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - trigger
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  api:
    build:
      context: .
      dockerfile: ./dockerfiles/api.Dockerfile
    container_name: api-instance
    ports:
      - "8000:8000"
    networks:
      - trigger
    depends_on:
      - db

volumes:
  postgres-data:
    driver: local
  mongo-data:
    driver: local

networks:
  trigger:
    driver: bridge
