services:
  db:
    container_name: trigger-db-instance
    image: mongo:7.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo_data:/data/db
    networks:
      - trigger
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"

  auth:
    container_name: trigger-auth-instance
    build:
      context: ..
      dockerfile: ./deploy/dockerfiles/auth.Dockerfile
    networks:
      - trigger
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_HOST: ${MONGO_HOST}
      MONGO_DB: ${MONGO_DB}

      AUTH_SERVICE_BASE_URL: ${AUTH_SERVICE_BASE_URL}
      USER_SERVICE_BASE_URL: ${USER_SERVICE_BASE_URL}
      SESSION_SERVICE_BASE_URL: ${SESSION_SERVICE_BASE_URL}
      SYNC_SERVICE_BASE_URL: ${SYNC_SERVICE_BASE_URL}
      SETTINGS_SERVICE_BASE_URL: ${SETTINGS_SERVICE_BASE_URL}
      WEB_BASE_URL: ${WEB_BASE_URL}

      ADMIN_TOKEN: ${ADMIN_TOKEN}
      TOKEN_SECRET: ${TOKEN_SECRET}
      AUTH_KEY: ${AUTH_KEY}
      AUTH_MAX_AGES: ${AUTH_MAX_AGES}
      AUTH_IS_PROD: ${AUTH_IS_PROD}

      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GITHUB_KEY: ${GITHUB_KEY}
      GITHUB_SECRET: ${GITHUB_SECRET}

      AUTH_PORT: ${AUTH_PORT}
    ports:
      - "${AUTH_PORT}:${AUTH_PORT}"

  user:
    container_name: trigger-user-instance
    build:
      context: ..
      dockerfile: ./deploy/dockerfiles/user.Dockerfile
    networks:
      - trigger
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_HOST: ${MONGO_HOST}
      MONGO_DB: ${MONGO_DB}

      AUTH_SERVICE_BASE_URL: ${AUTH_SERVICE_BASE_URL}
      USER_SERVICE_BASE_URL: ${USER_SERVICE_BASE_URL}
      SESSION_SERVICE_BASE_URL: ${SESSION_SERVICE_BASE_URL}
      SYNC_SERVICE_BASE_URL: ${SYNC_SERVICE_BASE_URL}
      SETTINGS_SERVICE_BASE_URL: ${SETTINGS_SERVICE_BASE_URL}

      ADMIN_TOKEN: ${ADMIN_TOKEN}

      USER_PORT: ${USER_PORT}
    ports:
      - "${USER_PORT}:${USER_PORT}"

  session:
    container_name: trigger-session-instance
    build:
      context: ..
      dockerfile: ./deploy/dockerfiles/session.Dockerfile
    networks:
      - trigger
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_HOST: ${MONGO_HOST}
      MONGO_DB: ${MONGO_DB}

      AUTH_SERVICE_BASE_URL: ${AUTH_SERVICE_BASE_URL}
      USER_SERVICE_BASE_URL: ${USER_SERVICE_BASE_URL}
      SESSION_SERVICE_BASE_URL: ${SESSION_SERVICE_BASE_URL}
      SYNC_SERVICE_BASE_URL: ${SYNC_SERVICE_BASE_URL}
      SETTINGS_SERVICE_BASE_URL: ${SETTINGS_SERVICE_BASE_URL}

      ADMIN_TOKEN: ${ADMIN_TOKEN}

      SESSION_PORT: ${SESSION_PORT}
    ports:
      - "${SESSION_PORT}:${SESSION_PORT}"

  sync:
    container_name: trigger-sync-instance
    build:
      context: ..
      dockerfile: ./deploy/dockerfiles/sync.Dockerfile
    networks:
      - trigger
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_HOST: ${MONGO_HOST}
      MONGO_DB: ${MONGO_DB}

      AUTH_SERVICE_BASE_URL: ${AUTH_SERVICE_BASE_URL}
      USER_SERVICE_BASE_URL: ${USER_SERVICE_BASE_URL}
      SESSION_SERVICE_BASE_URL: ${SESSION_SERVICE_BASE_URL}
      SYNC_SERVICE_BASE_URL: ${SYNC_SERVICE_BASE_URL}
      SETTINGS_SERVICE_BASE_URL: ${SETTINGS_SERVICE_BASE_URL}

      ADMIN_TOKEN: ${ADMIN_TOKEN}

      SYNC_PORT: ${SYNC_PORT}
    ports:
      - "${SYNC_PORT}:${SYNC_PORT}"

  settings:
    container_name: trigger-settings-instance
    build:
      context: ..
      dockerfile: ./deploy/dockerfiles/settings.Dockerfile
    networks:
      - trigger
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_HOST: ${MONGO_HOST}
      MONGO_DB: ${MONGO_DB}

      AUTH_SERVICE_BASE_URL: ${AUTH_SERVICE_BASE_URL}
      USER_SERVICE_BASE_URL: ${USER_SERVICE_BASE_URL}
      SESSION_SERVICE_BASE_URL: ${SESSION_SERVICE_BASE_URL}
      SYNC_SERVICE_BASE_URL: ${SYNC_SERVICE_BASE_URL}
      SETTINGS_SERVICE_BASE_URL: ${SETTINGS_SERVICE_BASE_URL}

      ADMIN_TOKEN: ${ADMIN_TOKEN}

      SETTINGS_PORT: ${SETTINGS_PORT}
    ports:
      - "${SETTINGS_PORT}:${SETTINGS_PORT}"

  action:
    container_name: trigger-action-instance
    build:
      context: ..
      dockerfile: ./deploy/dockerfiles/action.Dockerfile
    networks:
      - trigger
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_HOST: ${MONGO_HOST}
      MONGO_DB: ${MONGO_DB}

      AUTH_SERVICE_BASE_URL: ${AUTH_SERVICE_BASE_URL}
      USER_SERVICE_BASE_URL: ${USER_SERVICE_BASE_URL}
      SESSION_SERVICE_BASE_URL: ${SESSION_SERVICE_BASE_URL}
      ACTION_SERVICE_BASE_URL: ${ACTION_SERVICE_BASE_URL}
      GMAIL_SERVICE_BASE_URL: ${GMAIL_SERVICE_BASE_URL}

      ADMIN_TOKEN: ${ADMIN_TOKEN}

      ACTION_PORT: ${ACTION_PORT}
    ports:
      - "${ACTION_PORT}:${ACTION_PORT}"

  gmail:
    container_name: trigger-gmail-instance
    build:
      context: ..
      dockerfile: ./deploy/dockerfiles/gmail.Dockerfile
    networks:
      - trigger
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_HOST: ${MONGO_HOST}
      MONGO_DB: ${MONGO_DB}

      AUTH_SERVICE_BASE_URL: ${AUTH_SERVICE_BASE_URL}
      USER_SERVICE_BASE_URL: ${USER_SERVICE_BASE_URL}
      SESSION_SERVICE_BASE_URL: ${SESSION_SERVICE_BASE_URL}
      ACTION_SERVICE_BASE_URL: ${ACTION_SERVICE_BASE_URL}
      GMAIL_SERVICE_BASE_URL: ${GMAIL_SERVICE_BASE_URL}

      ADMIN_TOKEN: ${ADMIN_TOKEN}

      GMAIL_PORT: ${GMAIL_PORT}
    ports:
      - "${GMAIL_PORT}:${GMAIL_PORT}"

volumes:
  mongo_data:
    driver: local

networks:
  trigger:
    driver: bridge
